/**
 * Sync Figma Variables (semantic collection) -> tokens.css + Tailwind v4 @theme
 * Usage:
 *   npx tsx scripts/sync-figma-to-tokens.ts
 * Options:
 *   SYNC_DRY_RUN=1 npx tsx scripts/sync-figma-to-tokens.ts
 */

import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import TokenValidator, { TokenDefinition } from "./token-validator";

type Cfg = {
  figma: { collection: string; fileHint?: string };
  paths: { tokensCss: string; themeCss: string; backupDir: string };
  prefix: string;
  modes: { light: string; dark: string };
  types: { color: string[]; number: string[]; string: string[] };
  tailwind: { writeTheme: boolean; colorKeys: string[]; radiusKeys: string[] };
  dryRun: boolean;
};

// ---- Helpers ---------------------------------------------------------------

const readJSON = async <T>(p: string) => JSON.parse(await fs.readFile(p, "utf8")) as T;
const ensureDir = async (p: string) => fs.mkdir(p, { recursive: true });
const stamp = () => new Date().toISOString().replaceAll(":", "-").slice(0, 19);
const sha = (s: string) => crypto.createHash("sha1").update(s).digest("hex").slice(0, 7);

type VarRec = {
  name: string;             // e.g., color.brand.primary
  type: "color" | "number" | "string";
  light?: string | number;  // hex, number, string
  dark?: string | number;
};

// Decide variable type from name
const inferType = (name: string, cfg: Cfg): VarRec["type"] => {
  const hit = (arr: string[]) => arr.some((p) => name.startsWith(p));
  if (hit(cfg.types.color)) return "color";
  if (hit(cfg.types.number)) return "number";
  if (hit(cfg.types.string)) return "string";
  // default: color (most tokens will be colors)
  return "color";
};

// Build CSS vars from records
const buildTokensCss = (vars: VarRec[], cfg: Cfg) => {
  const toCssVar = (n: string) => `--${cfg.prefix}-${n.replaceAll(".", "-")}`;
  const lightLines: string[] = [];
  const darkLines: string[] = [];
  for (const v of vars) {
    if (v.light !== undefined) lightLines.push(`  ${toCssVar(v.name)}: ${v.light};`);
    if (v.dark !== undefined) darkLines.push(`  ${toCssVar(v.name)}: ${v.dark};`);
  }
  const header = `/* Generated by sync-figma-to-tokens.ts @ ${new Date().toISOString()} */
:root {
${lightLines.join("\n")}
}
`;
  const darkBlock = darkLines.length
    ? `
/* Dark mode overrides (match your app's data-theme or .dark class) */
:root.dark, [data-theme="dark"] {
${darkLines.join("\n")}
}
`
    : "";
  return header + darkBlock + "\n";
};

// Update Tailwind v4 @theme mapping (theme.css)
const updateThemeCss = async (themeCssPath: string, cfg: Cfg) => {
  let current = "";
  try { current = await fs.readFile(themeCssPath, "utf8"); } catch {}
  const lines: string[] = [];
  lines.push(`@import "./tokens.css";`);
  lines.push("");
  lines.push("@theme {");

  // Minimal core mapping (extend as needed)
  for (const key of cfg.tailwind.colorKeys) {
    lines.push(`  --color-${key}: var(--${cfg.prefix}-color-${key});`);
  }
  lines.push(`  --color-foreground: var(--${cfg.prefix}-color-foreground, #111827);`);
  lines.push(`  --color-background: var(--${cfg.prefix}-color-surface, #ffffff);`);

  for (const r of cfg.tailwind.radiusKeys) {
    lines.push(`  --radius-${r}: var(--${cfg.prefix}-radius-${r});`);
  }

  lines.push("}");
  const next = lines.join("\n") + "\n";

  if (current.trim() === next.trim()) return { wrote: false, hash: sha(next) };
  await fs.writeFile(themeCssPath, next, "utf8");
  return { wrote: true, hash: sha(next) };
};

// Pretty CLI table
const pad = (s: string, n: number) => (s.length >= n ? s : s + " ".repeat(n - s.length));

// ---- FIGMA MCP bridge (Cursor fills these) ---------------------------------

// Cursor's Figma MCP exposes functions. We'll try different possible function names.
const figma = {
  // Confirm the active file and return variable records from a collection with modes
  getVariablesFromCollection: async (collection: string, expectedFile?: string) => {
    // Try different possible MCP function names
    const possibleFunctions = [
      'get_design_context',
      'getDesignContext', 
      'get_design_context',
      'getVariableDefs',
      'get_variable_defs',
      'getVariableDefinitions'
    ];

    let ctx: any = null;
    let defs: any = null;

    // Try to get design context
    for (const funcName of possibleFunctions.slice(0, 3)) {
      try {
        // @ts-ignore – MCP injected in Cursor runtime
        ctx = await (globalThis as any).figma?.[funcName]?.();
        if (ctx) break;
      } catch (e) {
        // Continue to next function
      }
    }

    if (!ctx) {
      // Fallback: try to get variable definitions directly
      for (const funcName of possibleFunctions.slice(3)) {
        try {
          // @ts-ignore – MCP injected in Cursor runtime
          defs = await (globalThis as any).figma?.[funcName]?.();
          if (defs) break;
        } catch (e) {
          // Continue to next function
        }
      }
    }

    if (!ctx && !defs) {
      throw new Error("Figma MCP connection unavailable. Please ensure:\n1. Figma is open and you have a file active\n2. Cursor is connected to Figma MCP\n3. Your Figma access token is configured in .cursor/mcp.json");
    }

    if (expectedFile && ctx && !String(ctx.fileName || "").includes(expectedFile)) {
      console.warn(`⚠️ Active Figma file "${ctx.fileName}" does not match hint "${expectedFile}". Proceeding anyway.`);
    }

    // If we have context but no defs, try to get defs
    if (ctx && !defs) {
      for (const funcName of possibleFunctions.slice(3)) {
        try {
          // @ts-ignore – MCP injected in Cursor runtime
          defs = await (globalThis as any).figma?.[funcName]?.();
          if (defs) break;
        } catch (e) {
          // Continue to next function
        }
      }
    }

    if (!defs) {
      throw new Error("Could not retrieve variable definitions from Figma MCP");
    }

    const collectionDef = defs.collections?.find((c: any) => c.name === collection);
    if (!collectionDef) {
      const available = defs.collections?.map((c: any) => c.name).join(", ") || "none";
      throw new Error(`Collection "${collection}" not found. Available: ${available}`);
    }

    // Gather variables with light/dark values
    const recs: VarRec[] = [];
    for (const v of collectionDef.variables || []) {
      const name: string = v.name; // e.g., color.brand.primary
      const modes = v.modes || {};
      const light = modes.Light ?? modes.default ?? modes[Object.keys(modes)[0]];
      const dark = modes.Dark;
      recs.push({ name, type: "color", light, dark });
    }
    return recs;
  },
};

// ---- MAIN ------------------------------------------------------------------

(async () => {
  const cfg = await readJSON<Cfg>("scripts/figma-sync.config.json");

  // Allow env override for dry run
  const dry = cfg.dryRun || process.env.SYNC_DRY_RUN === "1";

  console.log(`\n🔄 Syncing Figma → Code
  • File hint: ${cfg.figma.fileHint ?? "(none)"}
  • Collection: ${cfg.figma.collection}
  • tokens.css: ${cfg.paths.tokensCss}
  • theme.css : ${cfg.paths.themeCss}
  • dry-run    : ${dry ? "YES" : "no"}
`);

  try {
    // 1) Fetch variables
    console.log("📡 Fetching variables from Figma...");
    const raw = await figma.getVariablesFromCollection(cfg.figma.collection, cfg.figma.fileHint);

    // 2) Infer types and normalize
    const vars: VarRec[] = raw.map((r) => ({
      ...r,
      type: inferType(r.name, cfg),
    }));

    // 3) Validate tokens before processing
    console.log("🔍 Validating tokens...");
    const validator = new TokenValidator(cfg);
    const tokenDefinitions: TokenDefinition[] = vars.map(v => ({
      name: v.name,
      type: v.type as 'color' | 'number' | 'string',
      value: v.light || v.dark || '',
      isSemantic: v.name.includes('brand') || v.name.includes('kpi') || v.name.includes('surface') || v.name.includes('text'),
      isPrimitive: v.name.includes('pi-color') || v.name.includes('pi-red') || v.name.includes('pi-green') || v.name.includes('pi-blue') || v.name.includes('pi-yellow')
    }));

    const validationResult = validator.validateCollection(tokenDefinitions);
    
    if (!validationResult.isValid) {
      console.log("\n⚠️  Validation Issues Found:");
      validationResult.errors.forEach(error => console.log(`  ❌ ${error}`));
      validationResult.warnings.forEach(warning => console.log(`  ⚠️  ${warning}`));
      validationResult.suggestions.forEach(suggestion => console.log(`  💡 ${suggestion}`));
      
      if (validationResult.errors.length > 0) {
        console.log("\n❌ Sync aborted due to validation errors");
        process.exit(1);
      }
    }

    // 4) Build tokens.css
    console.log("🏗️  Building tokens.css...");
    const nextTokens = buildTokensCss(vars, cfg);

    // 5) Read current tokens.css and write backups/diff
    let prevTokens = "";
    try { prevTokens = await fs.readFile(cfg.paths.tokensCss, "utf8"); } catch {}
    const changed = prevTokens.trim() !== nextTokens.trim();
    
    if (dry) {
      console.log(changed ? "🟡 tokens.css would change" : "✅ tokens.css already up to date");
    } else {
      if (changed) {
        await ensureDir(cfg.paths.backupDir);
        const backup = path.join(cfg.paths.backupDir, `tokens.${stamp()}.${sha(prevTokens)}.css`);
        if (prevTokens) await fs.writeFile(backup, prevTokens, "utf8");
        await fs.writeFile(cfg.paths.tokensCss, nextTokens, "utf8");
        console.log(`✅ tokens.css updated ${prevTokens ? `(backup: ${backup})` : ""}`);
      } else {
        console.log("✅ tokens.css unchanged");
      }
    }

    // 6) Optionally update @theme mapping
    if (cfg.tailwind.writeTheme) {
      console.log("🎨 Updating theme.css...");
      const res = dry ? { wrote: changed, hash: sha(nextTokens) } : await updateThemeCss(cfg.paths.themeCss, cfg);
      console.log(res.wrote ? `✅ theme.css updated (${res.hash})` : "✅ theme.css unchanged");
    }

    // 7) Print a compact summary
    console.log("\n📦 Variables synced:");
    const rows = vars
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((v) => `${pad(v.type, 6)}  ${pad(v.name, 28)}  L:${String(v.light ?? "").padEnd(10)}  D:${String(v.dark ?? "")}`);
    console.log(rows.join("\n"));

    // 8) Generate changelog
    if (changed && !dry) {
      await generateChangelog(vars, cfg);
    }

    console.log(`\n✨ Done. ${dry ? "(dry-run)" : ""}\n`);
    
  } catch (error) {
    console.error("❌ Sync failed:", error?.message || error);
    
    // Try to provide helpful error messages
    if (error?.message?.includes("Figma MCP connection unavailable")) {
      console.log("\n💡 Troubleshooting tips:");
      console.log("  1. Make sure Figma is open with a file active");
      console.log("  2. Check that Cursor is connected to Figma MCP");
      console.log("  3. Verify your Figma access token in .cursor/mcp.json");
    }
    
    process.exit(1);
  }
})();

// Generate changelog for token changes
async function generateChangelog(vars: VarRec[], cfg: Cfg): Promise<void> {
  try {
    const changelogPath = path.join(cfg.paths.backupDir, `changelog.${stamp()}.md`);
    const changelog = `# Token Sync Changelog - ${new Date().toISOString()}

## Summary
- **Total tokens:** ${vars.length}
- **Color tokens:** ${vars.filter(v => v.type === 'color').length}
- **Number tokens:** ${vars.filter(v => v.type === 'number').length}
- **String tokens:** ${vars.filter(v => v.type === 'string').length}

## Token Details
${vars.map(v => `- \`${v.name}\` (${v.type}): ${v.light || v.dark}`).join('\n')}

## Generated Files
- \`tokens.css\` - CSS custom properties
- \`theme.css\` - Tailwind theme configuration
`;
    
    await fs.writeFile(changelogPath, changelog, 'utf8');
    console.log(`📝 Changelog generated: ${changelogPath}`);
  } catch (error) {
    console.warn("⚠️  Could not generate changelog:", error?.message);
  }
}
